version: "2"
services:
  zeronet:
    container_name: zeronet
    image: chrisbensch/docker-zeronet:latest
    ports:
      - 26552:26552
      - 43110:43110
    environment:
      - ENABLE_TOR=true
      - UI_PASSWORD=password
    storage_opt:
      size: '8G'
    restart:
      always


